const numbers = [1, 2, 3, 4, 5, 6, 7, 4, 8, 9, 10];
console.log(numbers);
numbers.push(11, 12, 13);
console.log(numbers);
console.log(numbers.pop());
console.log(numbers);
console.log(numbers.unshift(0));
console.log(numbers);
console.log(numbers.shift());
console.log(numbers);
console.log(numbers.includes(40));
console.log(numbers.indexOf(4));
console.log(numbers.lastIndexOf(4));
console.log(numbers.join("|"));
const n2 = [20, 30, 40, 50, 60, 70, 80, 90, 100];
const n3 = n2;
console.log(numbers.concat(n2));
n2.splice(0, 0, 10);
console.log(n2);
